# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "amoeba-js-components-rails"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Barton, Amoeba Consulting LLC."]
  s.date = "2013-01-18"
  s.email = "cbarton@amoe.ba"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "amoeba-js-components-rails.gemspec",
    "lib/amoeba-js-components-rails.rb",
    "lib/amoeba_js_components_rails.rb",
    "lib/amoeba_js_components_rails/rails/engine.rb",
    "test/helper.rb",
    "test/test_amoeba-js-components-rails.rb",
    "vendor/assets/javascripts/amoeba-components.js.coffee",
    "vendor/assets/javascripts/amoeba-components/combo_button.js.coffee",
    "vendor/assets/javascripts/amoeba-components/form_watcher.js.coffee",
    "vendor/assets/javascripts/vendor/backbone.syphon.js"
  ]
  s.homepage = "http://github.com/cbarton/amoeba-js-components-rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Several components for the Amoeba JS framework"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

